### ISSUE TITLE
Technical Documentation Page link panel hides text...

### ISSUE THREAD

**Issue by astratow** [dyarawilliams/freeCodeCamp-projects#1]
link panel hides text in your Technical Documentation Page. I think I had similar issue and to resolve it I used their code and edited it promptly. I have no idea how it works.  All the best!

**Comment by dyarawilliams** [comment]
> link panel hides text in your Technical Documentation Page. I think I had similar issue and to resolve it I used their code and edited it promptly. I have no idea how it works. All the best!

Thanks, it is fixed now was missing a curly brace on one of my media queries.

**Comment by astratow** [comment]
Splendid work!
